### PR TITLE
add rails caching to social shares count

### PR DESCRIPTION
**Pull request by Chocksy**
I made this simple change for adding caching to the gem. It's using the Rails.cache that defaults to file_store in case there is no cache_store defined.

### CODE REVIEW

**Comment by Timrael** [comment]
Hi Chocksy!
First of all - good job. Cache is good, but now gem has big dependency - rails. It can't be used outside of rails. There are two options:
1. separate cache and rails
2. make a new gem, for example social_shares_rails and implement this logic there
How do you think which is better?

**Comment by Chocksy** [comment]
@Timrael if we want to not keep it dependent on rails the simplest and fastest solution would be to make a new gem. Doing a new class for caching would probably require some work from our part to support different storage systems. Do you agree?

**Comment by Timrael** [comment]
Yeah. I've created a new repo for it https://github.com/Timrael/social_shares_rails and have added you as collaborator. You can start it w/o me. I will have free time tomorrow and can help you. On 21 of December till 8 January I will be unreachable coz vacation.

**Comment by Chocksy** [comment]
@Timrael cool. Thanks for making a new repo. I'll try to push the changes there tomorrow. :+1:  I guess we can close this PR now.

**Pull request closed without merging**
