### PR TITLE
Don't use default timeouts of RestClient

### LINKED ISSUE #3: Don't use default timeouts of RestClient
Set them to about 3-6sec

### PR DESCRIPTION
**Pull request by Chocksy**
- we also rescue when there is a timeout or no response and return 0
- also changed the facebook url to `URL = 'http://api.facebook.com/restserver.php` the previous one was giving forbidden error.

fixes #3

### CODE REVIEW

**Comment by Timrael** [comment]
Hi, first of all thanks for PR :+1: .

1. defined timeouts are good
2. rescue #shares! 
As you can see this method has exclamation mark, it means by convention that it's ok to return exception in case of error. Now look at base.rb and there will be #shares method with rescue that you are looking for (https://github.com/Timrael/social_shares/blob/master/lib/social_shares/base.rb#L10-L15). 
 If you don't want to handle exceptions just use methods without exclamation mark. For example #selected instead of #selected!, #all instead of #all!, etc.
3. facebook endpoint
I have received feedback that this url produce too many errors, so I changed it on facebook FQL. Try it. If you have some problems with it, tell me please. 

So in sum, could you please save only defined timeouts in this PR?

**Comment by Chocksy** [comment]
2. @Timrael i agree with you i went overboard with the rescue. I decided to do that because i was already rescuing in my code. But i think we should make these kinds of methods i'm gonna try to make the changes.
3. The facebook endpoint just didn't work for me so once i updated it it started returning results. I tried it in the browser also and it didn't work.

I'll only do defined timeouts.

**Comment by Chocksy** [comment]
@Timrael i made the changes let me know if it feels better now. I now noticed i had the facebook old version i just rebased.

**Comment by Timrael** [comment]
@Chocksy I have merged the PR. Now we need to think how to make this timeouts editable from outside. Because there might be cases when someone wants to change them.

**Comment by Chocksy** [comment]
Yeah well an initializer might be a good idea. I'm trying to squeeze some time to get the caching done as that's what i'm more interested in. On our website http://www.epicpxls.com we disabled the gem as twitter was not very reliable in the last week. Caching should solve this.

**Comment by Chocksy** [comment]
So i was thinking of adding rack-cache or redis with both options and people being able to define the url for redis means we will have an initilizer that we can also set timeout on.

**Pull request closed without merging**
